export const LOGIN_SUCCESS              = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE              = 'LOGIN_FAILURE';
export const SIGNUP_SUCCESS             = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE             = 'SIGNUP_FAILURE';
export const LOGOUT_SUCCESS             = 'LOGOUT_SUCCESS';
export const AUTHENTICATE_USER_SUCCESS  = 'AUTHENTICATE_USER_SUCCESS';
export const AUTHENTICATE_USER_FAILURE  = 'AUTHENTICATE_USER_FAILURE';
export const SIMPLE_USER_LOGIN_SUCCESS  = 'SIMPLE_USER_LOGIN_SUCCESS';
export const SIMPLE_USER_REGISTER_SUCCESS = 'SIMPLE_USER_REGISTER_SUCCESS';
export const START_LOADING              = 'START_LOADING';
export const STOP_LOADING               = 'STOP_LOADING';
export const GET_USERS_DATA_SUCCESS     = 'GET_USERS_DATA_SUCCESS';
export const GET_USERS_DATA_FAILURE     = 'GET_USERS_DATA_FAILURE';

export const GET_HOME_SUCCESS                    = 'GET_HOME_SUCCESS';
export const GET_HOME_FAILURE                    = 'GET_HOME_FAILURE';
export const GET_TEMPLATES_BY_CATEGORY_SUCCESS   = 'GET_TEMPLATES_BY_CATEGORY_SUCCESS';
export const SET_SELECTED_TAB_ID                 = 'SET_SELECTED_TAB_ID';
export const SET_SELECTED_TEMPLATE               = 'SET_SELECTED_TEMPLATE';
export const UPDATE_FORM_MODAL                   = 'UPDATE_FORM_MODAL';
export const SET_PROFESSIONAL_SUMMARY            = 'SET_PROFESSIONAL_SUMMARY';
export const SET_IS_CROPPER_MODAL_OPEN           = 'SET_IS_CROPPER_MODAL_OPEN';
export const SET_INIT_HEADING                    = 'SET_INIT_HEADING';
export const SET_INIT_HEADING_TITLE              = 'SET_INIT_HEADING_TITLE';
export const SET_INTERESTS                       = 'SET_INTERESTS';
export const CLEAR_RESUME_FORM                   = 'CLEAR_RESUME_FORM';

export const CREATE_FIRST_EDUCATION              = 'CREATE_FIRST_EDUCATION';
export const CREATE_NEW_EDUCATION                = 'CREATE_NEW_EDUCATION';
export const DELETE_EDUCATION                    = 'DELETE_EDUCATION';
export const UPDATE_SPECIFIC_OBJECT_EDUCATION    = 'UPDATE_SPECIFIC_OBJECT_EDUCATION';

export const CREATE_FIRST_WORK_EXPERIENCE            = 'CREATE_FIRST_WORK_EXPERIENCE';
export const CREATE_NEW_WORK_EXPERIENCE              = 'CREATE_NEW_WORK_EXPERIENCE';
export const DELETE_WORK_EXPERIENCE                  = 'DELETE_WORK_EXPERIENCE';
export const UPDATE_SPECIFIC_OBJECT_WORK_EXPERIENCE  = 'UPDATE_SPECIFIC_OBJECT_WORK_EXPERIENCE';

export const CREATE_FIRST_SKILL              = 'CREATE_FIRST_SKILL';
export const CREATE_NEW_SKILL                = 'CREATE_NEW_SKILL';
export const DELETE_SKILL                    = 'DELETE_SKILL';
export const UPDATE_SPECIFIC_OBJECT_SKILL    = 'UPDATE_SPECIFIC_OBJECT_SKILL';

export const CREATE_FIRST_LANGUAGE             = 'CREATE_FIRST_LANGUAGE';
export const CREATE_NEW_LANGUAGE               = 'CREATE_NEW_LANGUAGE';
export const DELETE_LANGUAGE                   = 'DELETE_LANGUAGE';
export const UPDATE_SPECIFIC_OBJECT_LANGUAGE   = 'UPDATE_SPECIFIC_OBJECT_LANGUAGE';

export const CREATE_FIRST_PROJECT              = 'CREATE_FIRST_PROJECT';
export const CREATE_NEW_PROJECT                = 'CREATE_NEW_PROJECT';
export const DELETE_PROJECT                    = 'DELETE_PROJECT';
export const UPDATE_SPECIFIC_OBJECT_PROJECT    = 'UPDATE_SPECIFIC_OBJECT_PROJECT';

export const CREATE_FIRST_CERTIFICATION            = 'CREATE_FIRST_CERTIFICATION';
export const CREATE_NEW_CERTIFICATION              = 'CREATE_NEW_CERTIFICATION';
export const DELETE_CERTIFICATION                  = 'DELETE_CERTIFICATION';
export const UPDATE_SPECIFIC_OBJECT_CERTIFICATION  = 'UPDATE_SPECIFIC_OBJECT_CERTIFICATION';

export const CREATE_FIRST_SOCIAL_LINK              = 'CREATE_FIRST_SOCIAL_LINK';
export const CREATE_NEW_SOCIAL_LINK                = 'CREATE_NEW_SOCIAL_LINK';
export const DELETE_SOCIAL_LINK                    = 'DELETE_SOCIAL_LINK';
export const UPDATE_SPECIFIC_OBJECT_SOCIAL_LINK    = 'UPDATE_SPECIFIC_OBJECT_SOCIAL_LINK';

export const CREATE_FIRST_REFERENCE            = 'CREATE_FIRST_REFERENCE';
export const CREATE_NEW_REFERENCE              = 'CREATE_NEW_REFERENCE';
export const DELETE_REFERENCE                  = 'DELETE_REFERENCE';
export const UPDATE_SPECIFIC_OBJECT_REFERENCE  = 'UPDATE_SPECIFIC_OBJECT_REFERENCE';

export const CREATE_FIRST_EXTRA_CURRICULAR_ACTIVITY            = 'CREATE_FIRST_EXTRA_CURRICULAR_ACTIVITY';
export const CREATE_NEW_EXTRA_CURRICULAR_ACTIVITY              = 'CREATE_NEW_EXTRA_CURRICULAR_ACTIVITY';
export const DELETE_EXTRA_CURRICULAR_ACTIVITY                  = 'DELETE_EXTRA_CURRICULAR_ACTIVITY';
export const UPDATE_SPECIFIC_OBJECT_EXTRA_CURRICULAR_ACTIVITY  = 'UPDATE_SPECIFIC_OBJECT_EXTRA_CURRICULAR_ACTIVITY';

export const FETCH_BLOGS_START         = 'FETCH_BLOGS_START';
export const FETCH_BLOGS_SUCCESS       = 'FETCH_BLOGS_SUCCESS';
export const FETCH_BLOGS_ERROR         = 'FETCH_BLOGS_ERROR';
export const FETCH_BLOG_BY_ID_START    = 'FETCH_BLOG_BY_ID_START';
export const FETCH_BLOG_BY_ID_SUCCESS  = 'FETCH_BLOG_BY_ID_SUCCESS';
export const FETCH_BLOG_BY_ID_ERROR    = 'FETCH_BLOG_BY_ID_ERROR';
export const FETCH_BLOG_BY_SLUG_START   = 'FETCH_BLOG_BY_SLUG_START';
export const FETCH_BLOG_BY_SLUG_SUCCESS = 'FETCH_BLOG_BY_SLUG_SUCCESS';
export const FETCH_BLOG_BY_SLUG_ERROR   = 'FETCH_BLOG_BY_SLUG_ERROR';
export const CREATE_BLOG_START         = 'CREATE_BLOG_START';
export const CREATE_BLOG_SUCCESS       = 'CREATE_BLOG_SUCCESS';
export const CREATE_BLOG_ERROR         = 'CREATE_BLOG_ERROR';
export const UPDATE_BLOG_START         = 'UPDATE_BLOG_START';
export const UPDATE_BLOG_SUCCESS       = 'UPDATE_BLOG_SUCCESS';
export const UPDATE_BLOG_ERROR         = 'UPDATE_BLOG_ERROR';
export const DELETE_BLOG_START         = 'DELETE_BLOG_START';
export const DELETE_BLOG_SUCCESS       = 'DELETE_BLOG_SUCCESS';
export const DELETE_BLOG_ERROR         = 'DELETE_BLOG_ERROR';

export const FETCH_TEMPLATES_REQUEST   = 'FETCH_TEMPLATES_REQUEST';
export const FETCH_TEMPLATES_SUCCESS   = 'FETCH_TEMPLATES_SUCCESS';
export const FETCH_TEMPLATES_FAILURE   = 'FETCH_TEMPLATES_FAILURE';
export const CREATE_TEMPLATE_REQUEST   = 'CREATE_TEMPLATE_REQUEST';
export const CREATE_TEMPLATE_SUCCESS   = 'CREATE_TEMPLATE_SUCCESS';
export const CREATE_TEMPLATE_FAILURE   = 'CREATE_TEMPLATE_FAILURE';
export const UPDATE_TEMPLATE_REQUEST   = 'UPDATE_TEMPLATE_REQUEST';
export const UPDATE_TEMPLATE_SUCCESS   = 'UPDATE_TEMPLATE_SUCCESS';
export const UPDATE_TEMPLATE_FAILURE   = 'UPDATE_TEMPLATE_FAILURE';
export const DELETE_TEMPLATE_REQUEST   = 'DELETE_TEMPLATE_REQUEST';
export const DELETE_TEMPLATE_SUCCESS   = 'DELETE_TEMPLATE_SUCCESS';
export const DELETE_TEMPLATE_FAILURE   = 'DELETE_TEMPLATE_FAILURE';

export const FETCH_JOBS_REQUEST   = 'FETCH_JOBS_REQUEST';
export const FETCH_JOBS_SUCCESS   = 'FETCH_JOBS_SUCCESS';
export const FETCH_JOBS_FAILURE   = 'FETCH_JOBS_FAILURE';
export const CREATE_JOB_REQUEST   = 'CREATE_JOB_REQUEST';
export const CREATE_JOB_SUCCESS   = 'CREATE_JOB_SUCCESS';
export const CREATE_JOB_FAILURE   = 'CREATE_JOB_FAILURE';
export const UPDATE_JOB_REQUEST   = 'UPDATE_JOB_REQUEST';
export const UPDATE_JOB_SUCCESS   = 'UPDATE_JOB_SUCCESS';
export const UPDATE_JOB_FAILURE   = 'UPDATE_JOB_FAILURE';
export const DELETE_JOB_REQUEST   = 'DELETE_JOB_REQUEST';
export const DELETE_JOB_SUCCESS   = 'DELETE_JOB_SUCCESS';
export const DELETE_JOB_FAILURE   = 'DELETE_JOB_FAILURE';
